---
title: "Assignment 1: Introduction"
author: "Christopher Starr"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have been dabbling in computer science since highschool (I am 40 so a few years now). I have spent some time working with CRMs that have a different interface for working with data but intuitively work in similar ways. I did some of my core coursework at Duke/Sanford in R as a means to try to teach myself to use it. The rest of class we did in Stata which is another aspect of my experience. I have used Git for other projects over the years. 

2. Are there any components of the course about which you feel confident?

> Answer: I love learning software platforms and learning to code. R is awesome and I feel thus far its going well. 

3. Are there any components of the course about which you feel apprehensive?

> Answer: I am struggling with some of the conversations we have had about data. The words we use don't intuitively make sense to me and I am worried I might get behind understanding those aspects. 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: 

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
